# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

jobs:  
  include:
    - stage: "Deployment"
      go : 1.8                
      name:  "unit testing All"            
      script: - go build logins
              - go test logins/test/*.go
