# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

# Only the last two Go releases are supported by the Go team with security
# updates. Any older versions be considered deprecated. Don't bother testing
# with them.
go:
  - 1.9.x

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install:
  - go get -u github.com/gin-gonic/gin
  - go get -u github.com/stretchr/testify/asser
# script always runs to completion (set +e). If we have linter issues AND a

jobs:  
  include:
    - stage: "Login Pass"                
      name:  "LoginPass"            
      script: go test logins/test/login_pass_test.go
    - stage: "Login form user test"
      name:  "Login Form User Test"
      script: go test logins/test/form_user_test.go

